"use client";
import {ColorModeContext,useMode } from "../theme"
import { CssBaseline, ThemeProvider } from "@mui/material";
import Topbar from "@/components/Topbar";
import Sidebar from "@/components/Sidebar";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [theme,colorMode]=useMode()
  return (
    <html lang="en">
      <body className={inter.className}>
      <ColorModeContext.Provider value={colorMode}>
      <ThemeProvider theme={theme}>
        <CssBaseline/>
    <div className="App">
    <Sidebar/>
    <div className="main w-full">
      <Topbar/> 
      {children}
    </div>
      
      
    </div>
    </ThemeProvider>
    </ColorModeContext.Provider>
        
        
        </body>
    </html>
  );
}
